Fixed an error in bin/install and added force yes  mode for both install and uninstall scripts

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+do_uninstall() {
+  /opt/terrastories/bin/uninstall -y
+}
+
 do_install() {
   # Clone the terrastories repository to a known location in /opt/terrastories
   git clone https://github.com/rubyforgood/terrastories.git /opt/terrastories
@@ -18,12 +22,34 @@ do_install() {
   service start terrastories
 }
 
-while true; do
-    read -p "This is not a typical development command. It will install \
+prompt_for_install() {
+  while true; do
+      read -p "This is not a typical development command. It will install \
 terrastories as a service intended for a deployed production environment. Are \
 you sure you want to proceed? y/N " yn
-    case $yn in
-        [Yy]* ) bin/uninstall; do_install; break;;
-        * ) exit;;
-    esac
+      case $yn in
+          [Yy]* ) do_uninstall && do_install; break;;
+          * ) exit;;
+      esac
+  done
+}
+
+force_yes=false
+
+while getopts ":y" opt; do
+  case $opt in
+    y)
+      force_yes=true
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+  esac
 done
+
+if [ $force_yes == true ]; then
+  do_uninstall && do_install;
+else
+  prompt_for_install
+fi
diff --git a/bin/uninstall b/bin/uninstall
--- a/bin/uninstall
+++ b/bin/uninstall
@@ -8,12 +8,34 @@ do_uninstall() {
   rm -rf /opt/terrastories
 }
 
-while true; do
+prompt_for_uninstall() {
+  while true; do
     read -p "This is not a typical development command. It will uninstall \
 terrastories and remove all its related files from a deployed environment.\
 Are you sure you want to proceed? y/N " yn
     case $yn in
-        [Yy]* ) do_uninstall; break;;
-        * ) exit;;
+      [Yy]* ) do_uninstall; break;;
+      * ) exit;;
     esac
+  done
+}
+
+force_yes=false
+
+while getopts ":y" opt; do
+  case $opt in
+    y)
+      force_yes=true
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+  esac
 done
+
+if [ $force_yes == true ]; then
+  do_uninstall;
+else
+  prompt_for_uninstall
+fi
